# Generated by Django 5.2.2 on 2025-06-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name_task', models.TextField()),
                ('level', models.CharField(choices=[('easy', 'Жеңил'), ('medium', 'Орточо'), ('hard', 'Оор'), ('very_hard', 'Өтө оор')], max_length=20)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('task', 'Task'), ('in_progress', 'In Progress'), ('done', 'Done')], default='task', max_length=20)),
                ('programmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.programmer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.project')),
            ],
        ),
    ]
