# Generated by Django 5.2.2 on 2025-06-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='group',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('easy', 'Жеңил'), ('medium', 'Орточо'), ('hard', 'Оор'), ('very_hard', 'Өтө оор')], default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='name_task',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='programmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.programmer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.project'),
        ),
    ]
