# Generated by Django 5.2.1 on 2025-06-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_programmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='user',
        ),
    ]
